### ISSUE TITLE
Tighter line distance

### ISSUE THREAD

**Issue by tin2tin** [SpectralVectors/MindMapper#1]
If you add this line after 139, you'll get a tighter line distance(adding align after box is the trick)

        `box = box.column(align=True)`

Cool project, btw!

**Comment by SpectralVectors** [comment]
Thanks, I added it to the Image select/open boxes, but I left the Title/Color boxes separated.
Thanks for the suggestion, and for the interest. 

I think I'm going to try to add the ability to add/name inputs/outputs, as I saw that requested somewhere, then leave the rest for whoever wants to fork and extend it.

**Comment by tin2tin** [comment]
Thanks. People have been requesting mindmaps for the Blender Screenwriter add-on. I think it might be over-kill, but still it's very interesting to see what you're doing with mindmaps.

**Comment by SpectralVectors** [comment]
I misunderstood your comment at first, thinking, "I don't have a column after line 139, they must mean row." But I now realize that you were suggesting adding a column to tighten it up vertically, as well! That has now been done, too. More advanced features will have to wait, but at least I was able to get this closer to the way you suggested (I think)!

**Comment by tin2tin** [comment]
It's simply because I personally struggled to tighten lines vertically when using box. The reason is that box cancels alignment of columns, and the workaround is to add the alignment after defining the box. I just wanted to share this with you. 

Btw. looks brilliant with the image option. Maybe I would add the buttons after the content part of the node, as you would typically read from the top down, so the image and the node text will be on top.
