### ISSUE TITLE
You could load text from files

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [SpectralVectors/MindMapper#10]
It is easy

Just looks like:
[Comment Node](https://github.com/DeJhon-Huang/Blender_Comment_Node)
![image](https://github.com/SpectralVectors/MindMapper/assets/65578116/95687b69-8131-4e0b-b44a-6bf0121a9357)

**Comment by SpectralVectors** [comment]
Good suggestion, and thanks for linking to a current example, I have implemented the feature in the latest version, you can download it via the __Code__ button, but I may try to get the AI image feature working before I draft another release.
Thanks and enjoy!
