### ISSUE TITLE
Linking to text editor

### ISSUE THREAD

**Issue by tin2tin** [SpectralVectors/MindMapper#2]
If you want to improve the connection to the text editor, maybe this will be useful: https://github.com/gabrielmontagne/blender-addon-link-text-to-frame (I'm not entirely sure how it works). 

Gabriel did it because there was talk about adding mindmapping to then Blender Screenwriter add-on: https://github.com/gabrielmontagne/blender-addon-marker-preview-video/issues/1#issuecomment-770417986

**Comment by tin2tin** [comment]
Btw. do you know if it is possible to print out the nodes as text in the order they're linked(going from left to right)?

**Comment by SpectralVectors** [comment]
Those are some interesting ideas. Unfortunately, at this point, I'm not sure how to get any data back out of the nodes, this is my first time working with custom node editor types in Blender, but I did do a fair bit of work with extracting info from nodes for my Transmat addon, you can check that out, if you like, but I don't know of a solution to get anything working in the short term. Still, it's good to know what people are looking for, and anyone is welcome to create their own version if I'm moving too slowly, or not adding the features they want.
I'm leaving the issue open, hopefully it's something the addon can offer in the future!
